version: '3.4'
services:
  fit-backend:
    restart: always
    build: .
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - .:/home/fit
      - ~/.m2:/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run